version: '3.4'

networks:
  dev:
    driver: bridge

services:
  coin-api-info:
    image: ${DOCKER_REGISTRY-}coinapiinfo
    depends_on:
        - "coin-api.database"
    container_name: coin-api-info.api
    ports:
        - "8080:80" 
    build:
      context: .
      dockerfile: Coin-Api-Info/Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=coin-api.database;Port=5432;Database=coin-api;
        - ASPNETCORE_URLS=http://+:80
        - CoinApi__Client=CoinApiClient
        - CoinApi__ApiKey=DCEB8DF1-9E76-49AE-A6E2-511B597A2AC3
        
    networks:
        - dev

  coin-api.database:
    image: postgres:latest
    container_name: coin-api.database
    environment:
        POSTGRES_DB : coin-api
        POSTGRES_USER : postgres
        POSTGRES_PASSWORD : postgres
    ports:
        - 5434:5432
    volumes:
        - "chatto-db:/var/lib/postgresql/data"
    networks:
            - dev

volumes:
    chatto-db: